---
- name: Setup NGINX Server
  hosts: web
  remote_user: ubuntu
  become: yes

  tasks:


  - name: "apt-get update" 
    apt:
      update_cache: yes

  - name: Install NGINX Packages
    apt:
      name: nginx
      state: latest

  - name: Start Service
    service:
      name: nginx
      state: restarted
      enabled: yes
